---
title: "Mapa Presidentas Morelos"
author: "Juvenal Campos"
date: "11/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Presione en un municipio para abrir la ficha de información sobre las presidentas en dicho municipio.

```{r, cache=FALSE, message=FALSE, warning=FALSE, echo=FALSE, out.width = 800, out.height=800}
# Librerias
library(rvest)
library(tidyverse)
library(rebus)
library(leaflet)

# Aca cambie el nombre del archivo procesado a presidentes_morelos_verificado.xlsx
presidentes <- readxl::read_xlsx("presidentes_morelos_verificado.xlsx")

# Me quedo solo con las mujeres
presidentas <- presidentes %>% 
  filter(es_mujer == 1) %>% 
  mutate(CVEGEO = paste0("170", mpio)) %>% 
  mutate(Año_inicio = str_extract(periodo, 
                                  pattern = START %R% one_or_more(DGT)))


# Municipios
mpios <- sf::st_read("muni_2018gw.shp", quiet = TRUE) %>% 
  filter(CVE_ENT == "17") %>% 
  select(CVEGEO, NOM_ENT, NOM_MUN) %>% 
  mutate(CVEGEO = as.character(CVEGEO))

# Claves de municipio 
claves_municipio <- mpios %>% 
  as_tibble() %>% 
  select(CVEGEO, NOM_MUN)

# Pego datos de poblacion (INEGI, Encuesta Intercensal 2015)
pop_muni <- tibble::tribble(
  ~CVEGEO,   ~ANIO,     ~Pob,
  17001L, 2015L,  17772L,
  17002L, 2015L,  22079L,
  17003L, 2015L,  35689L,
  17004L, 2015L,  85521L,
  17005L, 2015L,   9768L,
  17006L, 2015L, 194786L,
  17007L, 2015L, 366321L,
  17008L, 2015L,  99493L,
  17009L, 2015L,  19231L,
  17010L, 2015L,  17238L,
  17011L, 2015L, 214137L,
  17012L, 2015L,  57121L,
  17013L, 2015L,  15690L,
  17014L, 2015L,   9967L,
  17015L, 2015L,  26713L,
  17016L, 2015L,  18580L,
  17017L, 2015L,  66435L,
  17018L, 2015L, 116143L,
  17019L, 2015L,  27187L,
  17020L, 2015L,  46946L,
  17021L, 2015L,   7772L,
  17022L, 2015L,  20698L,
  17023L, 2015L,   7166L,
  17024L, 2015L,  52110L,
  17025L, 2015L,  33844L,
  17026L, 2015L,  17714L,
  17027L, 2015L,  11992L,
  17028L, 2015L,  68984L,
  17029L, 2015L, 102690L,
  17030L, 2015L,  52651L,
  17031L, 2015L,  36159L,
  17032L, 2015L,   9370L,
  17033L, 2015L,  15844L)

# Pegamos a presidentas el nombre de clave de municipio 
presidentas <- merge(presidentas,claves_municipio, by = "CVEGEO") %>% 
  merge(pop_muni, by = "CVEGEO")

# Genero Atributos para mapa. Requiero Municipio y Numero
atributos <- presidentas %>%
  group_by(CVEGEO, NOM_MUN) %>%
  summarise(Numero_presidentas = n(),
            Informacion_presidentas = paste0("<b style = 'color:green;'>Municipio: </b>", first(NOM_MUN), "<br>",
                                             "<b style = 'color:green;'>Población (2015): </b>", prettyNum(first(Pob), big.mark = ","), " habitantes<br>",
                                             paste0("<b>Nombre: </b>", Nombre, "<br>",
                                                    "<b>Periodo: </b>", periodo, "<br>",
                                                    "<b>Partido: </b>", Partido, "<br>",
                                                    collapse = "<br>")) )

# Juntamos geometrias y atributos:  
mapa <- merge(mpios, atributos, all.x = TRUE)  %>% 
  mutate(Numero_presidentas = ifelse(is.na(Numero_presidentas), 
                                    yes = 0, 
                                    no = Numero_presidentas))

# Hacemos el mapa: 
pal_color <- colorFactor(domain = unique(mapa$Numero_presidentas), 
                          palette = "magma", 
                          na.color = "gray")

# Hacemos el mapa
mapa %>% 
  leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(color = "white",
              dashArray = c(1,1),
              weight = 0.7,
              popup = mapa$Informacion_presidentas,
              fillColor = pal_color(mapa$Numero_presidentas), 
              opacity = 1, 
              fillOpacity = 0.8) %>% 
  addLegend(pal = pal_color, 
            values = mapa$Numero_presidentas, 
            position = "bottomright",
            title = "Numero de presidentas<br>que ha tenido cada municipio<br><b style = 'color:red'>Estado de Morelos</b>")

```
